version: "3"

services:
  workspace:
    build:
      context: ./nginx/
    container_name: miduner_framework
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
        - .:/var/www/html
        - ./nginx:/var/log/nginx
        - ./php-fpm/php-fpm.log:/var/log/php-fpm.log
        - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
    links: 
        - mysql

  mysql:
    image: mysql:5.6
    container_name: miduner_mysql
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password  
